packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  '@prisma/engines': false
  '@swc/core': false
  bcrypt: true
  msgpackr-extract: false
  msw: false
  prisma: true
  unrs-resolver: false
