---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCYvgvuAGpaqS1K4Qir1TeZU7dPwWdixgv309lF0oEs6kyRIGIMySERnAzEKu9cj4x/Fs+q+ul8yZBTkoAT3oZh2GA7mrgRpGq+GPr1Cjj0SBqLYyNSpG/Abwwh2qrw1E791NhckKr2vNsUNBqLgpUOqHMctaPG8bXiVfZOTj4tdi/wXy9uHakquQBuu1EifaMc3HMDiapbzT2ARjqe9sOsCUYVbFgcb4MwTooORbRwR57c9vOVrlv84AEi4T1dPv+jwRgNmH8ALJDVGtYuTsQ828jPh0ZHQjfcp+jZ9dHqH/9BuQVSwsFkWNfjZoArxJPd6g3h35Ox5fMRPbmgTcHiMykk7FzprV4WmqzVM0b55m1a+gYRnpPwc/tkEs1VkplZdumMuxv7LeAcPCSokv7o3t3qn1Tlxv/U+hLq20g/lamYOqdK6QOuhreuChtjYDEtN/t4TFTs7Mw61+7OiX/rRWX/Ya77b7jbDUDNCqTAltbSQVjDOcUqKT31tOodDoAFe3oeYF84+e9RDosjbHpWQscfExt463liWPMbNACSUfFlcUE1ShRs9FdBPf4QLBSHec8W00AdzlH4fIjFrTnhgRTRqmMikEF+5s1z93yeRdUSEXwbILwrkT7uwlBnavRgQoDZOiEMtTU1BLXZEUjNz1UP40svGhD6cHrx1fRhF3gq/RNcrimj+Jjvpks42U3U3Dgm3ZJja3iweZGYO49D/TAMXKRM+mqaz4j8ZjWGVQ==
    admin-user: AgA2eN8XyqfaokiWAyC6yP7JQRDsnMo5ClC6SMzsm4wWr+tKblKCV66oOl5UGEMbL61L3TaQneHDCF3z5ZLdVSpR7QPyjibjVM7U6gnI70GpBzEzbCSxQvJkLcBdRPQqsDzBJXDzM40v9Iqo7SeiTOQSK4rQwuoJ54MtKp1nJDe5/4G458jTaF8eOfgdZuq0DUBK0Nf5OTVh/hbu6l7H906DL9ko8Ae06pfZGXxVQq0/4nfQ5LluB30MX03F9fjEzar23oDAZLp2vL6t1JF4fg1it3ibf3L1jJBCiRTnGeRqYLj/69ylhh0QVLEiEbxoBfATO0fJwwNItScYSDsn6GgyifCN7mqyRoTZKsQ0v38u3YS4Q241Rr9RkHWv7avp3CSRxfN7jbZK/zqREFyn4Cs1EpzBcp6MbcyJEp5eAutf9BzNOmsnyOX/2fqtM8hIf3TH+EFaJ2jn7jtf5ad4J1XPb+eR8pkWti+KHvL4FwgPXhMhQL5tJuSc8PZqA7uEAL0iGktQy9lfM2Z22cmd/+h8USg2B4bRoUGe8t22APDnZ2udKoCj0+J7DOMaRiJxSztm2ORNTPHSDIEPOVOW/LLIiX9mF8pwU0tg6nL1AshE/w/97SetfV5QJAVu3qn8G/WM5Pt3PvPf+h9PNGZdCgPlaFgVQkq3bK3xGyP5mbmOaPR5C4aJmPHng7nT1UfPEsI5S09zGA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
