apiVersion: v1
kind: Secret
metadata:
  name: wafizo-secrets
  namespace: wafizo
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@localhost:5432/wafizo"
  REDIS_URL: "redis://localhost:6379"
  JWT_SECRET: "VOTRE_JWT_SECRET"
  GOOGLE_CLIENT_ID: "VOTRE_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "VOTRE_GOOGLE_CLIENT_SECRET"
  STRIPE_SECRET_KEY: "VOTRE_STRIPE_SECRET_KEY"
  BREVO_API_KEY: "VOTRE_BREVO_API_KEY"
  ALERTMANAGER_SMTP_PASSWORD: "VOTRE_APP_PASSWORD_GMAIL"
